version: '2'

services:
  phpfpm:
    build: .
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./:/var/www/upsidedowntext.online/

  nginx:
    image: nginx
    ports:
      - "80:80"
    links:
      - phpfpm
    volumes:
      - ./docker/nginx/default:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/logs:/var/log/nginx
    volumes_from:
      - phpfpm

  redis:
    image: "redis:alpine"